# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pywerami.ui'
#
# Created: Thu Apr 10 21:59:05 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(818, 559)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pywerami.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.listView = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout.addWidget(self.listView)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.levelstab = QtGui.QWidget()
        self.levelstab.setObjectName(_fromUtf8("levelstab"))
        self.formLayout = QtGui.QFormLayout(self.levelstab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.levelstab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.levelmin = QtGui.QLineEdit(self.levelstab)
        self.levelmin.setObjectName(_fromUtf8("levelmin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.levelmin)
        self.label_5 = QtGui.QLabel(self.levelstab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.levelmax = QtGui.QLineEdit(self.levelstab)
        self.levelmax.setObjectName(_fromUtf8("levelmax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.levelmax)
        self.setlevels = QtGui.QRadioButton(self.levelstab)
        self.setlevels.setChecked(True)
        self.setlevels.setObjectName(_fromUtf8("setlevels"))
        self.stepGroup = QtGui.QButtonGroup(MainWindow)
        self.stepGroup.setObjectName(_fromUtf8("stepGroup"))
        self.stepGroup.addButton(self.setlevels)
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.setlevels)
        self.levelnum = QtGui.QLineEdit(self.levelstab)
        self.levelnum.setObjectName(_fromUtf8("levelnum"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.levelnum)
        self.setstep = QtGui.QRadioButton(self.levelstab)
        self.setstep.setObjectName(_fromUtf8("setstep"))
        self.stepGroup.addButton(self.setstep)
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.setstep)
        self.levelstep = QtGui.QLineEdit(self.levelstab)
        self.levelstep.setObjectName(_fromUtf8("levelstep"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.levelstep)
        self.linlevel = QtGui.QRadioButton(self.levelstab)
        self.linlevel.setChecked(True)
        self.linlevel.setObjectName(_fromUtf8("linlevel"))
        self.levelGroup = QtGui.QButtonGroup(MainWindow)
        self.levelGroup.setObjectName(_fromUtf8("levelGroup"))
        self.levelGroup.addButton(self.linlevel)
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.linlevel)
        self.cdflevel = QtGui.QRadioButton(self.levelstab)
        self.cdflevel.setObjectName(_fromUtf8("cdflevel"))
        self.levelGroup.addButton(self.cdflevel)
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cdflevel)
        self.tabWidget.addTab(self.levelstab, _fromUtf8(""))
        self.styletab = QtGui.QWidget()
        self.styletab.setObjectName(_fromUtf8("styletab"))
        self.formLayout_2 = QtGui.QFormLayout(self.styletab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.styletab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.mapstyle = QtGui.QComboBox(self.styletab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapstyle.sizePolicy().hasHeightForWidth())
        self.mapstyle.setSizePolicy(sizePolicy)
        self.mapstyle.setObjectName(_fromUtf8("mapstyle"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.mapstyle)
        self.label_2 = QtGui.QLabel(self.styletab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.opacity = QtGui.QSlider(self.styletab)
        self.opacity.setMaximum(100)
        self.opacity.setProperty("value", 100)
        self.opacity.setOrientation(QtCore.Qt.Horizontal)
        self.opacity.setObjectName(_fromUtf8("opacity"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.opacity)
        self.fillstyle = QtGui.QCheckBox(self.styletab)
        self.fillstyle.setObjectName(_fromUtf8("fillstyle"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.fillstyle)
        self.contcheckmap = QtGui.QRadioButton(self.styletab)
        self.contcheckmap.setObjectName(_fromUtf8("contcheckmap"))
        self.contourGroup = QtGui.QButtonGroup(MainWindow)
        self.contourGroup.setObjectName(_fromUtf8("contourGroup"))
        self.contourGroup.addButton(self.contcheckmap)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.contcheckmap)
        self.contchecknone = QtGui.QRadioButton(self.styletab)
        self.contchecknone.setObjectName(_fromUtf8("contchecknone"))
        self.contourGroup.addButton(self.contchecknone)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.contchecknone)
        self.contcheckcolor = QtGui.QRadioButton(self.styletab)
        self.contcheckcolor.setChecked(True)
        self.contcheckcolor.setObjectName(_fromUtf8("contcheckcolor"))
        self.contourGroup.addButton(self.contcheckcolor)
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.contcheckcolor)
        self.contcolor = QtGui.QPushButton(self.styletab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contcolor.sizePolicy().hasHeightForWidth())
        self.contcolor.setSizePolicy(sizePolicy)
        self.contcolor.setStyleSheet(_fromUtf8("background-color: #000000"))
        self.contcolor.setText(_fromUtf8(""))
        self.contcolor.setObjectName(_fromUtf8("contcolor"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.contcolor)
        self.contlabel = QtGui.QCheckBox(self.styletab)
        self.contlabel.setObjectName(_fromUtf8("contlabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.contlabel)
        self.tabWidget.addTab(self.styletab, _fromUtf8(""))
        self.processtab = QtGui.QWidget()
        self.processtab.setObjectName(_fromUtf8("processtab"))
        self.formLayout_3 = QtGui.QFormLayout(self.processtab)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_11 = QtGui.QLabel(self.processtab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.resample = QtGui.QSpinBox(self.processtab)
        self.resample.setPrefix(_fromUtf8(""))
        self.resample.setMinimum(1)
        self.resample.setMaximum(10)
        self.resample.setObjectName(_fromUtf8("resample"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.resample)
        self.label_7 = QtGui.QLabel(self.processtab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.filtersize = QtGui.QSpinBox(self.processtab)
        self.filtersize.setPrefix(_fromUtf8(""))
        self.filtersize.setMinimum(1)
        self.filtersize.setMaximum(10)
        self.filtersize.setObjectName(_fromUtf8("filtersize"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.filtersize)
        self.smoothlabel = QtGui.QLabel(self.processtab)
        self.smoothlabel.setObjectName(_fromUtf8("smoothlabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.smoothlabel)
        self.filtersigma = QtGui.QDoubleSpinBox(self.processtab)
        self.filtersigma.setPrefix(_fromUtf8(""))
        self.filtersigma.setDecimals(1)
        self.filtersigma.setMaximum(4.0)
        self.filtersigma.setSingleStep(0.1)
        self.filtersigma.setObjectName(_fromUtf8("filtersigma"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.filtersigma)
        self.label_8 = QtGui.QLabel(self.processtab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.clipmin = QtGui.QLineEdit(self.processtab)
        self.clipmin.setObjectName(_fromUtf8("clipmin"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.clipmin)
        self.label_9 = QtGui.QLabel(self.processtab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.clipmax = QtGui.QLineEdit(self.processtab)
        self.clipmax.setObjectName(_fromUtf8("clipmax"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.clipmax)
        self.tabWidget.addTab(self.processtab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(250, 0))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.matplot = QtGui.QVBoxLayout()
        self.matplot.setSpacing(0)
        self.matplot.setObjectName(_fromUtf8("matplot"))
        self.verticalLayout_3.addLayout(self.matplot)
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setAllowedAreas(QtCore.Qt.LeftToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSaveas = QtGui.QAction(MainWindow)
        self.actionSaveas.setObjectName(_fromUtf8("actionSaveas"))
        self.actionProperties = QtGui.QAction(MainWindow)
        self.actionProperties.setObjectName(_fromUtf8("actionProperties"))
        self.actionHome = QtGui.QAction(MainWindow)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionPan = QtGui.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionAxes = QtGui.QAction(MainWindow)
        self.actionAxes.setObjectName(_fromUtf8("actionAxes"))
        self.actionSavefig = QtGui.QAction(MainWindow)
        self.actionSavefig.setObjectName(_fromUtf8("actionSavefig"))
        self.actionGrid = QtGui.QAction(MainWindow)
        self.actionGrid.setCheckable(True)
        self.actionGrid.setObjectName(_fromUtf8("actionGrid"))
        self.action3D = QtGui.QAction(MainWindow)
        self.action3D.setCheckable(True)
        self.action3D.setObjectName(_fromUtf8("action3D"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSaveas)
        self.menu_File.addAction(self.actionSavefig)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionImport)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionProperties)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menuView.addAction(self.actionAxes)
        self.menuView.addAction(self.action3D)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveas)
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addAction(self.actionAxes)
        self.toolBar.addAction(self.actionSavefig)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGrid)
        self.toolBar.addAction(self.action3D)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionProperties)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyWerami 3", None))
        self.label_3.setText(_translate("MainWindow", "Dependent variables:", None))
        self.label_4.setText(_translate("MainWindow", "Minimum", None))
        self.label_5.setText(_translate("MainWindow", "Maximum", None))
        self.setlevels.setText(_translate("MainWindow", "Levels", None))
        self.setstep.setText(_translate("MainWindow", "Step", None))
        self.linlevel.setText(_translate("MainWindow", "Linear", None))
        self.cdflevel.setText(_translate("MainWindow", "CDF based", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.levelstab), _translate("MainWindow", "Levels", None))
        self.label.setText(_translate("MainWindow", "Color map", None))
        self.label_2.setText(_translate("MainWindow", "Opacity", None))
        self.fillstyle.setText(_translate("MainWindow", "Filled contours", None))
        self.contcheckmap.setText(_translate("MainWindow", "Colormap", None))
        self.contchecknone.setText(_translate("MainWindow", "None", None))
        self.contcheckcolor.setText(_translate("MainWindow", "Single color", None))
        self.contlabel.setText(_translate("MainWindow", "Labeling", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.styletab), _translate("MainWindow", "Style", None))
        self.label_11.setText(_translate("MainWindow", "Resampling grid", None))
        self.label_7.setText(_translate("MainWindow", "Median filter size", None))
        self.smoothlabel.setText(_translate("MainWindow", "Gauss filter sigma", None))
        self.label_8.setText(_translate("MainWindow", "Clip minimum", None))
        self.label_9.setText(_translate("MainWindow", "Clip maximum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processtab), _translate("MainWindow", "Processing", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open pywerami project", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save pywerami project", None))
        self.actionImport.setText(_translate("MainWindow", "&Read tab", None))
        self.actionImport.setToolTip(_translate("MainWindow", "Read werami tab file", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit", None))
        self.actionSaveas.setText(_translate("MainWindow", "Save as...", None))
        self.actionSaveas.setToolTip(_translate("MainWindow", "Save as", None))
        self.actionProperties.setText(_translate("MainWindow", "Options", None))
        self.actionProperties.setToolTip(_translate("MainWindow", "Options", None))
        self.actionHome.setText(_translate("MainWindow", "Home", None))
        self.actionHome.setToolTip(_translate("MainWindow", "Default zoom", None))
        self.actionPan.setText(_translate("MainWindow", "Pan", None))
        self.actionPan.setToolTip(_translate("MainWindow", "Pan", None))
        self.actionZoom.setText(_translate("MainWindow", "Zoom", None))
        self.actionZoom.setToolTip(_translate("MainWindow", "Zoom to rectangle", None))
        self.actionAxes.setText(_translate("MainWindow", "Plot properties", None))
        self.actionAxes.setToolTip(_translate("MainWindow", "Plot properties", None))
        self.actionSavefig.setText(_translate("MainWindow", "Export figure...", None))
        self.actionSavefig.setToolTip(_translate("MainWindow", "Export figure", None))
        self.actionGrid.setText(_translate("MainWindow", "Grid", None))
        self.actionGrid.setToolTip(_translate("MainWindow", "Show grid", None))
        self.action3D.setText(_translate("MainWindow", "3D", None))
        self.action3D.setToolTip(_translate("MainWindow", "View active variable in 3D", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About PyWerami", None))

